### PR TITLE
Update to v0.2

### PR DESCRIPTION
**Pull request by synapticarbors**
This PR updates BioPandas to v0.2 and re-renders the feedstock to get python 3.6

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks a lot! Weird question: is there a way to test this locally before I merge?  Sth. `like conda install -c https://github.com/synapticarbors/biopandas-feedstock.git biopandas` ? Sry, have never worked with conda-forge PRs; is there some convention regarding PRs, like 2x [+1 MRG] or so?

**Comment by synapticarbors** [comment]
@rasbt Typically, conda-forge leaves testing to the upstream package distributer and only really tests for the existence of the resulting libraries via imports:

http://conda-forge.github.io/docs/testing.html#simple-existence-tests

And although I've never done this, I *think* you can go into the feedstock repo and run `conda build recipe` and then run `conda create -n test-biopandas biopandas --use-local` to build a new conda environment using the locally built binaries, activate the environment (`source activate test-biopandas`) and then do any testing you want.

**Comment by souravsingh** [comment]
LGTM.

**Comment by rasbt** [comment]
Thanks for the info @synapticarbors 

Looks good to me as well, will merge then :)

**Pull request merged**
