### PR TITLE
bump version to 0.2.3

### PR DESCRIPTION
**Pull request by rasbt**

### CODE REVIEW

**Comment by souravsingh** [comment]
Could you close and reopen the PR again? There seems to be a problem in CircleCI.

**Comment by souravsingh** [comment]
@conda-forge-admin please rerender

**Comment by rasbt** [comment]
thanks for looking into this. let's see if the circleci tests pass this time ...

**Comment by rasbt** [comment]
```
Source cache directory is: /feedstock_root/build_artefacts/src_cache
Downloading source to cache: biopandas-0.2.3.tar.gz
Downloading https://pypi.io/packages/source/b/biopandas/biopandas-0.2.3.tar.gz
Error: HTTP 404 NOT FOUND for url <https://pypi.io/packages/source/b/biopandas/biopandas-0.2.3.tar.gz>
Elapsed: 00:00.543930

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download biopandas-0.2.3.tar.gz
+ exit 1
Exited with code 1
``` 

Hm, this is weird as the link is valid for me: https://pypi.io/packages/source/b/biopandas/biopandas-0.2.3.tar.gz

**Comment by rasbt** [comment]
I restarted the Travis CI run and it passes now. I think the previous error was probably due to caching, because I uploaded the package to PyPI only ~30 min before I opened the PR here. I also restarted the other CI tests and hope it's working now.

**Comment by souravsingh** [comment]
Weirdly enough. Now Appveyor is failing due to outdated PR.

**Comment by rasbt** [comment]
@souravsingh Hm, it looks all fine to me now (no failing tests listed), is there something that needs to be fixed or is it good to merge?

**Pull request merged**
