### PR TITLE
Update to version 0.2.5.

### PR DESCRIPTION
**Pull request by moorepants**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by moorepants** [comment]
The patch is required due to https://github.com/rasbt/biopandas/issues/63

**Comment by moorepants** [comment]
@rasbt and @souravsingh, this is ready to be reviewed and merged.

**Comment by rasbt** [comment]
Thanks a lot. This looks all good to me, and since the tests pass also, I am happy to merge it.

**Pull request merged**
